### ISSUE TITLE
SpireClientException("Could not create channel")

### ISSUE THREAD

**Issue by lancelakey** [spire-io/spire.io.py#1]
# ESSS.
## ERROR: test_create_and_publish_to_default_channel (test.test_spire.TestSpireClient)

Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/spire.io.py/test/test_spire.py", line 137, in test_create_and_publish_to_default_channel
    second_client_channel = self.get_client()[0].session().channel()
  File "spire/core.py", line 195, in channel
    raise SpireClientException("Could not create channel")
SpireClientException: Could not create channel
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): build.spire.io
requests.packages.urllib3.connectionpool: DEBUG: "GET / HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): build.spire.io
requests.packages.urllib3.connectionpool: DEBUG: "POST /sessions HTTP/1.1" 201 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): build.spire.io
requests.packages.urllib3.connectionpool: DEBUG: "POST /channels HTTP/1.1" 201 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): build.spire.io
requests.packages.urllib3.connectionpool: DEBUG: "GET / HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): build.spire.io
requests.packages.urllib3.connectionpool: DEBUG: "POST /sessions HTTP/1.1" 201 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): build.spire.io
requests.packages.urllib3.connectionpool: DEBUG: "POST /channels HTTP/1.1" 409 None
--------------------- >> end captured logging << ---------------------

---

Ran 5 tests in 0.441s

FAILED (SKIP=3, errors=1)

**Comment by thedaniel** [comment]
this should work now, and CI is green.
